import { BriefcaseBusiness, Building2, UsersRound } from "lucide-react"

export const dummyJobs = [
  {
    title: "Technical Support Specialist",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Senior UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Marketing Officer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Junior Graphic Designer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Interaction Designer",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Project Manager",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Software Engineer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Visual Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "UI/UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Product Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Networking Engineer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Front End Developer",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Senior UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Marketing Manager",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
]

export const dummyEmployer = [
  { company: "TechNova", openings: 3 },
  { company: "InnoWave", openings: 5 },
  { company: "NextGen Solutions", openings: 2 },
  { company: "SkyHigh Tech", openings: 7 },
  { company: "QuantumLeap", openings: 1 },
  { company: "CodeCraft", openings: 4 },
  { company: "DevSphere", openings: 6 },
  { company: "CyberNest", openings: 3 },
  { company: "Pixel Perfect", openings: 5 },
  { company: "SwiftSoft", openings: 8 },
  { company: "BrightByte", openings: 2 },
  { company: "NeuralWorks", openings: 6 },
  { company: "BlueOcean Tech", openings: 3 },
  { company: "FutureFlow", openings: 4 },
  { company: "AI Nexus", openings: 7 },
  { company: "CloudMinds", openings: 2 },
  { company: "EcoLogic", openings: 5 },
  { company: "DigitalHive", openings: 3 },
  { company: "Web Wizards", openings: 4 },
  { company: "CodeNinjas", openings: 6 },
  { company: "Quantum Coders", openings: 2 },
  { company: "DataForge", openings: 7 },
  { company: "LogicLayer", openings: 3 },
  { company: "ByteBridge", openings: 5 },
  { company: "SoftScape", openings: 6 },
  { company: "AI Horizon", openings: 4 },
  { company: "TechTide", openings: 3 },
  { company: "SmartCircuit", openings: 2 },
  { company: "AppPulse", openings: 5 },
  { company: "CyberEdge", openings: 7 },
  { company: "NextOrbit", openings: 4 },
  { company: "NeonTech", openings: 6 },
  { company: "Infinity Apps", openings: 3 },
  { company: "Vortex Software", openings: 5 },
  { company: "AI Sentinel", openings: 2 },
  { company: "CloudXperts", openings: 6 },
  { company: "RapidDevelop", openings: 4 },
  { company: "BinaryBrains", openings: 3 },
  { company: "CodeSprint", openings: 7 },
  { company: "MetaLogic", openings: 5 },
  { company: "OmniSoft", openings: 2 },
  { company: "DataZen", openings: 6 },
  { company: "WebSync", openings: 3 },
  { company: "NeoTech", openings: 4 },
  { company: "AgileMinds", openings: 5 },
  { company: "FutureBit", openings: 6 },
  { company: "TechnoSpark", openings: 2 },
  { company: "MindFusion", openings: 3 },
  { company: "NetGenius", openings: 4 },
  { company: "Innovate IT", openings: 7 },
]

export const dummyData = {
  analytics: [
    {
      number: "1.75,324",
      title: "Live job",
      Icon: BriefcaseBusiness,
    },
    {
      number: "97,856",
      title: "Companies",
      Icon: Building2,
    },
    {
      number: "38,47,154",
      title: "Candidates",
      Icon: UsersRound,
    },
    {
      number: "1,568",
      title: "New Jobs",
      Icon: BriefcaseBusiness,
    },
  ],
  popularVacancies: [
    {
      title: "Full-Stack Dev",
      numbers: "45,904",
    },
    {
      title: "Product Manager",
      numbers: "4,339",
    },
    {
      title: "Web Designer",
      numbers: "20,065",
    },
    {
      title: "Front-End Dev",
      numbers: "74,821",
    },
    {
      title: "Cloud Engineer",
      numbers: "39,556",
    },
    {
      title: "UI/UX Designer",
      numbers: "55,382",
    },
    {
      title: "Blockchain Dev",
      numbers: "8,569",
    },
    {
      title: "Data Scientist",
      numbers: "7,586",
    },
  ],
}
