import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "@/styles/globals.css"

import { Footer } from "@/components/Footer"
import { HomeNav } from "@/components/home/HomeNav"
import RootProvider from "@/components/RootProvider"

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} h-screen w-screen overflow-x-hidden antialiased`}
      >
        <RootProvider>
          <HomeNav />
          {children}
          <Footer />
        </RootProvider>
      </body>
    </html>
  )
}
