export const navLinks = {
  home: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Jobs",
      href: "/find-jobs",
    },
    {
      label: "Find Employers",
      href: "/find-employers",
    },
    {
      label: "Find Candidates",
      href: "/find-candidates",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
  candidate: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Jobs",
      href: "/jobs",
    },
    {
      label: "Find Employers",
      href: "/employers",
    },

    {
      label: "Dashboard",
      href: "/dashboard",
    },
    {
      label: "Job Alerts",
      href: "/job-alerts",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
  employers: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Candidates",
      href: "/find-candidates",
    },
    {
      label: "Dashboard",
      href: "/dashboard",
    },
    {
      label: "My Jobs",
      href: "/my-jobs",
    },
    {
      label: "Applications",
      href: "/applications",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
}

export const footerLinks = {
  quickLinks: [
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Contact",
      href: "/contact",
    },
    {
      label: "Pricing",
      href: "/pricing",
    },
  ],
  candidates: [
    {
      label: "Browse Jobs",
      href: "/find-jobs",
    },
    {
      label: "Browse Employers",
      href: "/employers",
    },
    {
      label: "Candidate Dashboard",
      href: "/dashboard",
    },
    {
      label: "Saved Jobs",
      href: "/saved-jobs",
    },
  ],
  employers: [
    {
      label: "Post a Job",
      href: "/post-job",
    },
    {
      label: "Browse Candidates",
      href: "/candidates",
    },
    {
      label: "Employers Dashboard",
      href: "/dashboard",
    },
    {
      label: "Applications",
      href: "/applications",
    },
  ],
  support: [
    {
      label: "Faqs",
      href: "/faqs",
    },
    {
      label: "Privacy Policy",
      href: "/privacy-policy",
    },
    {
      label: "Terms & Conditions",
      href: "/terms-and-conditions",
    },
  ],
}

export const cities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Surat",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri & Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan & Dombivali",
  "Vasai Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Haora",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli and Dharwad",
  "Bareilly",
  "Moradabad",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Mira and Bhayander",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Guntur",
  "Bikaner",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai Nagar",
  "Warangal",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Nanded Waghala",
  "Kolapur",
  "Ajmer",
]

export const dummyJobs = [
  {
    title: "Technical Support Specialist",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Senior UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Marketing Officer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Junior Graphic Designer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Interaction Designer",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Project Manager",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Software Engineer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Visual Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "UI/UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Product Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Networking Engineer",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Front End Developer",
    type: "PART-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Senior UX Designer",
    type: "FULL-TIME",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
  {
    title: "Marketing Manager",
    type: "INTERNSHIP",
    salary: "$20,000 - $25,000",
    company: "Google Inc.",
    location: "Dhaka, Bangladesh",
  },
]

export const dummyEmployer = [
  { company: "TechNova", openings: 3 },
  { company: "InnoWave", openings: 5 },
  { company: "NextGen Solutions", openings: 2 },
  { company: "SkyHigh Tech", openings: 7 },
  { company: "QuantumLeap", openings: 1 },
  { company: "CodeCraft", openings: 4 },
  { company: "DevSphere", openings: 6 },
  { company: "CyberNest", openings: 3 },
  { company: "Pixel Perfect", openings: 5 },
  { company: "SwiftSoft", openings: 8 },
  { company: "BrightByte", openings: 2 },
  { company: "NeuralWorks", openings: 6 },
  { company: "BlueOcean Tech", openings: 3 },
  { company: "FutureFlow", openings: 4 },
  { company: "AI Nexus", openings: 7 },
  { company: "CloudMinds", openings: 2 },
  { company: "EcoLogic", openings: 5 },
  { company: "DigitalHive", openings: 3 },
  { company: "Web Wizards", openings: 4 },
  { company: "CodeNinjas", openings: 6 },
  { company: "Quantum Coders", openings: 2 },
  { company: "DataForge", openings: 7 },
  { company: "LogicLayer", openings: 3 },
  { company: "ByteBridge", openings: 5 },
  { company: "SoftScape", openings: 6 },
  { company: "AI Horizon", openings: 4 },
  { company: "TechTide", openings: 3 },
  { company: "SmartCircuit", openings: 2 },
  { company: "AppPulse", openings: 5 },
  { company: "CyberEdge", openings: 7 },
  { company: "NextOrbit", openings: 4 },
  { company: "NeonTech", openings: 6 },
  { company: "Infinity Apps", openings: 3 },
  { company: "Vortex Software", openings: 5 },
  { company: "AI Sentinel", openings: 2 },
  { company: "CloudXperts", openings: 6 },
  { company: "RapidDevelop", openings: 4 },
  { company: "BinaryBrains", openings: 3 },
  { company: "CodeSprint", openings: 7 },
  { company: "MetaLogic", openings: 5 },
  { company: "OmniSoft", openings: 2 },
  { company: "DataZen", openings: 6 },
  { company: "WebSync", openings: 3 },
  { company: "NeoTech", openings: 4 },
  { company: "AgileMinds", openings: 5 },
  { company: "FutureBit", openings: 6 },
  { company: "TechnoSpark", openings: 2 },
  { company: "MindFusion", openings: 3 },
  { company: "NetGenius", openings: 4 },
  { company: "Innovate IT", openings: 7 },
]
