export const navLinks = {
  home: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Jobs",
      href: "/jobs",
    },
    {
      label: "Employers",
      href: "/employers",
    },
    {
      label: "Candidates",
      href: "/candidates",
    },
    {
      label: "Pricing Plans",
      href: "/pricing",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
  candidate: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Jobs",
      href: "/jobs",
    },
    {
      label: "Find Employers",
      href: "/employers",
    },

    {
      label: "Dashboard",
      href: "/dashboard",
    },
    {
      label: "Job Alerts",
      href: "/job-alerts",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
  employers: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Find Candidates",
      href: "/find-candidates",
    },
    {
      label: "Dashboard",
      href: "/dashboard",
    },
    {
      label: "My Jobs",
      href: "/my-jobs",
    },
    {
      label: "Applications",
      href: "/applications",
    },
    {
      label: "Customer Support",
      href: "/support",
    },
  ],
}

export const cities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Surat",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri & Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan & Dombivali",
  "Vasai Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Haora",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli and Dharwad",
  "Bareilly",
  "Moradabad",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Mira and Bhayander",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Guntur",
  "Bikaner",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai Nagar",
  "Warangal",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Nanded Waghala",
  "Kolapur",
  "Ajmer",
]
